### ISSUE TITLE
Generating the TLS certificate at runtime

### ISSUE THREAD

**Issue by andrejacobs** [BiAtoms/Socket.swift#10]
Hi, Thank you very much for the libraries Socket.swift and HTTP.swift.

I need to generate the certificate used by the HTTP server (and thus the TLS.swift file used in Socket.swift) at runtime. That is to say I need to generate a new certificate everytime the app is launched and I start up the server.

Do you know of any way that this can be achieved on iOS?

I have searched far and wide and it seems most people end up shipping a copy of OpenSSL in their app to do this. I am guessing that if I ended up doing this, then I would need export compliance and sign off from the US government / Apple to do this.

**Comment by OrkhanAlikhanov** [comment]
Hey! I don't know if iOS has an api to generate self signed certificates, but googling it revealed [this](https://stackoverflow.com/q/14072051). It does not seem to be part of supported API.
However, it seems [this library](https://github.com/svdo/swift-SelfSignedCert) is able to generate certificates. 

>I am guessing that if I ended up doing this, then I would need export compliance and sign off from the US government / Apple to do this.

Interesting, why would you?

**Comment by andrejacobs** [comment]
Thank you for the reply. I will take a look at the library and SO answer.

So as I understand it, when you submit an app to Apple they will ask you some questions regarding the use of encryption. This process has now changed and they require you to answer yes even if you use the Apple frameworks (i.e. ATS + HTTPS means you are using encryption). I am guessing that if I were to bundle OpenSSL with the app then I will have to go through more steps to get an export certificate (or whatever they call it) from the US government.
