### ISSUE TITLE
use it in app extension failed!

### ISSUE THREAD

**Issue by ribencong** [BiAtoms/Socket.swift#11]
Extension com.ribencong.blockchainPipe.TunProxy died unexpectedly
[TunProxy:75295] SyscallError: setpriority(PRIO_DARWIN_ROLE, 75295, 3): No such process
[TunProxy:75295] Remove assertion: <BKProcessAssertion: 0x100d7d6c0; "com.apple.extension.session" (extension:inf); id:…85104422BD2F>
-CMSessionMgr- CMSessionMgrHandleApplicationStateChange: CMSession: Client com.ribencong.blockchainPipe.TunProxy with pid '75295' is now Background Running. Background entitlement: NO LongFormVideoApp: NO
1177: pid 75295(TunProxy)

**Comment by OrkhanAlikhanov** [comment]
Can't tell anything from the provided info. Closing
