### ISSUE TITLE
Getting connection error using swift 4

### ISSUE THREAD

**Issue by jitendrasamcom84** [BiAtoms/Socket.swift#14]
Hello,

I implemented the code in my demo project but it seems that I am making some mistake and hence I am getting the connection error saying that connection refused. I tried with the port and the IP address. Could you please suggest me how can I solve this? Below I am sending you the code which I have implemented.

**Client Side:**
do {
            let client = try Socket(.inet, type: .stream, protocol: .tcp) // create client socket
            do {
                try client.connect(port: 8080, address: "192.168.1.50")
            }
            catch {
                print(error)
            }
            var buffer = [UInt8](repeating: 0, count: helloBytes.count) // allocate buffer
            let numberOfReadBytes = try client.read(&buffer, size: helloBytes.count)
            print(numberOfReadBytes == helloBytes.count) // true
            print(buffer == helloBytes) // true
            client.close()
        }
        catch {
            print(error)
        }
**Server Side**
do {
            let server = try Socket(.inet, type: .stream, protocol: .tcp) // create server socket
            do {
                try server.set(option: .reuseAddress, true) // set SO_REUSEADDR to 1
            }
            catch {
                print(error)
            }
            
            do {
                try server.bind(port: 8080, address:"192.168.1.88" ) // bind 'localhost:8090' address to the socket
            }
            catch {
                print(error)
            }
            
            do {
                try server.listen() // allow incoming connections
            }
            catch {
                print(error)
            }
//            server.close()
            let clientAtServerside = try server.accept() // accept client connection
            try clientAtServerside.write(helloBytes) // sending bytes to the client
            clientAtServerside.close()
        }
        catch {
            print(error)
        }

Please kindly provide the solution for this.

**Comment by OrkhanAlikhanov** [comment]
For server, pass nil for address in bind method. 
```
try server.bind(port: 8080, address: nil )
```
