### ISSUE TITLE
Ubuntu 16.04 does not build

### ISSUE THREAD

**Issue by chrigu1981** [BiAtoms/Socket.swift#16]
i get a warning if i try to build my project
```
warning: you may be able to install libtls using your system-packager:
     apt-get install libressl
```

installing ` apt-get install libressl` does not find the package

errors on building 
`.build/checkouts/CLibreSSL/clibressl.h:4:10: error: 'tls.h' file not found`
`.build/checkouts/Socket.swift/Sources/TLS.swift:12:12: error: could not build C module 'CLibreSSL'`

**Comment by OrkhanAlikhanov** [comment]
Hey! Check out #12
