### ISSUE TITLE
how can I make a real server cycle !?

### ISSUE THREAD

**Issue by kenculate** [BiAtoms/Socket.swift#6]
please make an example that socket server wait for a client to connect and have a conversation like a chat room with multi user!

**Comment by OrkhanAlikhanov** [comment]
Hey! You're basically asking for an XMPP server, which is really heavy and generally a team work. I don't believe I'll create that soon, but I was working on an XMPP client called [Xmpp.swift](https://github.com/BiAtoms/Xmpp.swift). It's under construction right now, but once it's done, we can create apps like telegram, whatsapp etc.

**Comment by OrkhanAlikhanov** [comment]
I am closing this. Thank you
