### ISSUE TITLE
cellular radio activitation

### ISSUE THREAD

**Issue by victorstewart** [BiAtoms/Socket.swift#8]
apple documentation reads that POSIX sockets will not activate the cellular radio... but I read things on stackoverflow saying it does (users had succesfully accomplished it)... then another user said the radio died after a little bit, with others being surprised.

do you have any final word on this, given this library exists? thanks!

**Comment by OrkhanAlikhanov** [comment]
Well, this library is just a wrapper around POSIX sockets, nothing more except TLS layer which also sends and reads data via raw sockets.

**Comment by victorstewart** [comment]
right ya I was just curious if you had used it on an iOS device exclusively over cellular (wifi disbaled), and gotten everything to work. essentially, can POSIX sockets use the cellular radio on iOS devices.

**Comment by OrkhanAlikhanov** [comment]
Yeah, a POSIX socket in iOS will definitely connect over cellular data just like wifi.
